# ============================================================
# Run or Raise - PPPP Leader Keymap
# ============================================================
#
# Leader key:
#   F19
#
# Physical mappings:
#   ThinkPad Right Alt -> Kanata -> F19
#   QMK keyboards      -> KC_F19
# ============================================================

# Direct
<Super>e,nautilus,org.gnome.Nautilus,

# B - Browser
F19 b z,zen-browser,zen,
F19 b c,google-chrome-stable,google-chrome,

# D - Develop
F19 d d,ghostty,com.mitchellh.ghostty,
F19 d f,heynote,Heynote,

# M - Media
F19 m s,spotify-launcher,Spotify,

# N - Network
F19 n v,nordvpn-gui,nordvpn-gui,
