[".config/1Password/ssh/agent.toml"]
    type = "file"
    encrypted = false
    {{- if and (eq .chezmoi.os "linux") (.chezmoi.kernel.osrelease | lower | contains "microsoft") }}
    path = "/mnt/c/Users/{{ .chezmoi.username }}/AppData/Local/1Password/config/agent.toml"
    {{- else }}
    contents = """[[ssh-keys]]
account = "https://my.1password.com/"
"""
    {{- end }}
